queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - status-success=nventive.UnoApplicationTemplate
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - label=ready-to-merge
      - label!=do-not-merge/breaking-change
      - label!=do-not-merge/work-in-progress
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=nventive.UnoApplicationTemplate
    merge_method: merge

pull_request_rules:

  - name: automatic merge for allcontributors pull requests
    conditions:
      - author=allcontributors[bot]
    actions:
      merge:
        method: merge
  - name: automatic strict merge when CI passes, has 2 reviews, no requests for change
      and is labeled 'ready-to-merge' unless labelled 'do-not-merge/breaking-change'
      or 'do-not-merge/work-in-progress'
    conditions: []
    actions:
      queue:
